apiVersion: v1
kind: Service
metadata:
  labels:
    app: carts
  name: carts
  namespace: ms-prod
spec:
  ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: carts
    deploymentconfig: carts
  sessionAffinity: None
  type: ClusterIP

kind: Service
metadata:
  labels:
    app: orders
  name: orders
  namespace: ms-prod
spec:
  ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: orders
    deploymentconfig: orders
  sessionAffinity: None
  type: ClusterIP
  
kind: Service
metadata:
  labels:
    app: shipping
  name: shipping
  namespace: ms-prod
spec:
  ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: shipping
    deploymentconfig: shipping
  sessionAffinity: None
  type: ClusterIP
